version: "3.6"

services:
    rabbitmq:
        container_name: votechain-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password        
        image: rabbitmq:3-management
        networks:
          - votechain-network
        
    seq:
        image: datalust/seq:latest
        container_name: votechain-seq
        ports:
          - '5341:80'
        environment:
          - ACCEPT_EULA=Y
        networks:
          - votechain-network
          
    sql:
        image: mcr.microsoft.com/mssql/server
        container_name: votechain-sql
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=Password1
        ports:
          - "1433:1433"
        networks:
          - votechain-network

networks:
  votechain-network:
    name: votechain-network